const LOGIN_REQUEST_TOPIC = "loginRequest1";
const LOGIN_RESPONSE_TOPIC = "loginResponse1";
const SIGNUP_REQUEST_TOPIC = 'signUpRequest1';
const SIGNUP_RESPONSE_TOPIC = 'signUpResponse1';

module.exports = {
    LOGIN_REQUEST_TOPIC, LOGIN_RESPONSE_TOPIC,
    SIGNUP_REQUEST_TOPIC, SIGNUP_RESPONSE_TOPIC
}
