const LOGIN_REQUEST_TOPIC = "loginRequest1";
const LOGIN_RESPONSE_TOPIC = "loginResponse1";
const SIGNUP_REQUEST_TOPIC = 'signUpRequest1';
const SIGNUP_RESPONSE_TOPIC = 'signUpResponse1';
const PASSPORT_REQUEST_TOPIC = 'passportRequest1';
const PASSPORT_RESPONSE_TOPIC = 'passportResponse1';
const LIST_PROPERTY_REQUEST_TOPIC = "listPropertyRequest1"
const LIST_PROPERTY_RESPONSE_TOPIC = "listPropertyResponse1";
const DETAIL_PROPERTY_REQUEST_TOPIC='detailPropertyRequest1';
const DETAIL_PROPERTY_RESPONSE_TOPIC ='detailPropertyResponse1';
const PROFILE_VIEW_REQUEST_TOPIC ='profileViewRequestTopic1';
const PROFILE_VIEW_RESPONSE_TOPIC ='profileViewResponseTopic1';
const PROFILE_UPDATE_REQUEST_TOPIC = 'profileUpdateRequest1';
const  PROFILE_UPDATE_RESPONSE_TOPIC = 'profileUpdateResponse1';

module.exports = {
    LOGIN_REQUEST_TOPIC, LOGIN_RESPONSE_TOPIC,
    SIGNUP_REQUEST_TOPIC, SIGNUP_RESPONSE_TOPIC,
    PASSPORT_REQUEST_TOPIC, PASSPORT_RESPONSE_TOPIC,
    LIST_PROPERTY_REQUEST_TOPIC, LIST_PROPERTY_RESPONSE_TOPIC,
    DETAIL_PROPERTY_REQUEST_TOPIC, DETAIL_PROPERTY_RESPONSE_TOPIC,
    PROFILE_VIEW_REQUEST_TOPIC, PROFILE_VIEW_RESPONSE_TOPIC,
    PROFILE_UPDATE_REQUEST_TOPIC, PROFILE_UPDATE_RESPONSE_TOPIC,
 };