export const FETCH_PROPERTIES_LIST = "FETCH_PROPERTIES_LIST";
export const FETCH_PROPERTY_DETAIL = "FETCH_PROPERTY_DETAIL";
export const SEARCH_FILTER_CRITERIA = "SEARCH_FILTER_CRITERIA";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";